### ISSUE TITLE
Feature request: Toggle SageMaker endpoints On and Off

### ISSUE THREAD

**Issue by vadimaws** [aws-samples/aws-genai-llm-chatbot#165]
Some of the models deployed as SageMaker endpoints (e.g. HF img-2-txt) make use of very large g5.xl48 instances. In cases when this solution is deployed as experimentation playground, being able to switch these endpoints OFF and On (for example from the Models dashboard) could be highly beneficial from cost savings perspective.

**Comment by smilinrobin** [comment]
@bigadsoleiman  - Would you know of the high level steps for achieving this feature? Or can you guide us? 
And maybe we can update it in our local fork (or get a PR going)?

**Comment by ajaylamba-provar** [comment]
It would be a good feature to save cost while exploring the chatbot. Currently sagemaker models are costing too much even if they are not being utilised.

**Comment by flamingquaks** [comment]
I was reviewing this pain point after leaving the g5.48xl instance running for too long. 
I think at this point in time there's no way to set an endpoint as on/off or to 0 capacity. 

I'd propose removing the SageMaker endpoint deployment from the CDK stack and move it into a Step Function. This would enable the endpoint to be decoupled from the CDK/CFT deployment and be spun up and down. 

In addition the the ability to spin up/down, you can also set a cloudwatch alarm that is triggered after X minutes of inactivity, which could invoke the spin down automatically. This would help ensure resources aren't forgetfully left on.

To ensure the SageMaker endpoints are deleted if the stack is deleted, a Custom Resource could be deployed in the CDK stack with no actual action on create/update, but for delete would trigger deletion of matching SageMaker endpoints.

**Comment by azaylamba** [comment]
Currently the Sagemaker models are being used to utilize cross encoding for the responses. We can disable cross encoding and also the deployment for Sagemaker endpoints. With this approach, if someone don't want to use cross encoding, Sagemaker endpoints can be avoided.
I am exploring the option to make cross encoding option to avoid Sagemaker costs.

**Comment by flamingquaks** [comment]
I'd like to also throw in that we should have a clear breakdown in our docs of the costs associated with each configuration element. Maybe we can create a dedicate cost breakdown document to explain this.

**Comment by azaylamba** [comment]
Agree, that would help those who are trying this as an experimental prototype.

**Comment by flamingquaks** [comment]
I am currently working on a refactoring of the stack to support toggling. 

My current approach is to shift the SageMaker models into Service Catalog Products in a Portfolio. 
I plan to grant the Rest API service role access to launch products/ delete products. In the UI, the user would be able to request the resources and the UI would reflect the launch state. 

I'm also looking at including a CloudWatch alarm that monitors the model's invocation metrics and if there isn't invocations on the model in `x` minutes, it will trigger a lambda to tear down the product. 

I'm shifting the model config parameter from a single ssm parameter to multiple SSM parameters under a common param path. This allows the list models functionality to pull the model parms very much how it's done today, but as new products are spun up/down, their parameter data will automatically be removed, updating what's available for use. 

My current approach is to take care of the standard SageMaker models that are deployed, then attempt to work on the LangChain and Idefics interfaces. Since there are more dependencies on these, they are going to be a bit more complicated. 

Open for feedback if there's any!
