### ISSUE TITLE
Feature request: Option to register/signup users

### ISSUE THREAD

**Issue by ajaylamba-provar** [aws-samples/aws-genai-llm-chatbot#177]
Currently there is no option for registration/signup for users. This feature would make onboarding new users easy and quick.

**Comment by nagelpat** [comment]
This can be easily done by changing two booleans in the code since Cognito and the Amplify Authenticator library offer this out of the box.

[Cognito User Pool](https://github.com/aws-samples/aws-genai-llm-chatbot/blob/4f1b0bacb8eca8f6d3bb0a1bff8d3e919ba24e0f/lib/authentication/index.ts#L16)

[Amplify Auth lib](https://github.com/aws-samples/aws-genai-llm-chatbot/blob/4f1b0bacb8eca8f6d3bb0a1bff8d3e919ba24e0f/lib/user-interface/react-app/src/components/app-configured.tsx#L142C28-L142C28)

**Comment by ajaylamba-provar** [comment]
@nagelpat Thanks, should I make the changes and raise a PR or this has not been done intentionally and we won't be doing it?

**Comment by arm-diaz** [comment]
@ajaylamba-provar This is done intentionally. If you enable the registration, anybody who has access to the CloudFront Distribution will be able to sign up and use the application. I believe this was designed like this for security reasons. Otherwise, you will need a VPN or another mechanism to prevent unwanted users from registering and accessing the application.

**Comment by ajaylamba-provar** [comment]
Hmm ok. Makes sense.
Closing this then.
