### ISSUE TITLE
Support API Gateway based models

### ISSUE THREAD

**Issue by athewsey** [aws-samples/aws-genai-llm-chatbot#33]
Hi team & thanks for the cool sample!

To help support workshop cases where where Bedrock is not yet available and temporary accounts have too-restrictive quotas to deploy LLMs directly... It would be useful if this sample could also support [langchain.llms.AmazonAPIGateway](https://python.langchain.com/docs/integrations/llms/amazon_api_gateway) based models?

For example we could then deploy a Falcon 40B SageMaker endpoint on one or two large-size instances, and use it across workshop/hackathon teams by sharing the API URL (and optionally auth token) with participants.

**Comment by bigadsoleiman** [comment]
Hi @athewsey,

this can already be achieved today since the model interface can supports all [langchain integrations](https://python.langchain.com/docs/integrations/llms/). 

You'll need an [adapter](https://github.com/aws-samples/aws-genai-llm-chatbot/tree/main/lib/model-interfaces/langchain/functions/request-handler/adapters) that exposes [AmazonAPIGateway](https://python.langchain.com/docs/integrations/llms/amazon_api_gateway) as `get_llm` (see GPT example [here](https://github.com/aws-samples/aws-genai-llm-chatbot/blob/main/lib/model-interfaces/langchain/functions/request-handler/adapters/openai/gpt.py)), something along these lines

```python
import os

from langchain.llms import AmazonAPIGateway

from ..base import ModelAdapter
from ..registry import registry


class APIGatewayAdapter(ModelAdapter):
    def __init__(self, model_id, *args, **kwargs):
        self.model_id = model_id

        super().__init__(*args, **kwargs)

    def get_llm(self, model_kwargs={}):
        api_url = "https://<api_gateway_id>.execute-api.<region>.amazonaws.com/stage"
        return AmazonAPIGateway(api_url=api_url)


# Register the adapter to match your model ID from UI
registry.register(r"^apigateway*", APIGatewayAdapter)
```
