### ISSUE TITLE
Enhancement: Customization of Prompts after RAG Execution

### ISSUE THREAD

**Issue by samuelbaruffi** [aws-samples/aws-genai-llm-chatbot#72]
**Enhancement Proposal:**
- Allow customers the flexibility to customize their prompts post-RAG. This will enable a more dynamic way of interacting with the chatbot, allowing customers to potentially achieve better results through prompt engineering.

**Benefits:**
- Prompt Engineering: Customers will have a hands-on approach to experiment with different prompts and refine their chatbot queries, potentially leading to more accurate or desirable responses.
- User Customization: Offering this flexibility can help cater to a wider range of user requirements and use-cases.
- Enhanced User Experience: It can make the chatbot feel more interactive and user-friendly.

**Comment by massi-ang** [comment]
Great idea. Bouncing some thoughts about UX:

We have now the concept of workspace that defines the document retriever and the associated document to be used for RAG. We could then introduce the concept of a "chat persona", defined as a combination of an LLM and a set of prompts. The "default chat persona" for an LLM would be the one provided by Langchain `ConversationalRetrieverChain`. Additional personas can then be added by customizing the prompts. 

In the Chatbot playground, one would then chose the "chat persona" instead of the LLM.

One could also introduce a testing playground, where it could be possible to add up to 5 combinations of chat personas and workspaces, and compare the results on a given set of queries (consider this a separate feature)
